image: node:lts

cache:
  paths:
    - node_modules/

stages:
  - eslint
  - selenium

Eslint:
  stage: eslint
  before_script:
    - npm install
  script:
    - npm run eslint

MyJob:
    stage:


Selenium:
  stage: eslint
  before_script:
    # Install Java, unzip, python3
    - apt-get update
    - apt-get install -y default-jdk unzip
    - apt-get install -y python3 python3-pip
    - pip3 install selenium
    # Install chrome
    - wget --quiet https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - dpkg -i google-chrome-stable_current_amd64.deb || apt-get -qq install -y -f
    - dpkg -i google-chrome-stable_current_amd64.deb
    # Install chromedriver
    - wget https://chromedriver.storage.googleapis.com/77.0.3865.40/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - mv chromedriver /usr/bin/chromedriver
    - chmod +x /usr/bin/chromedriver
  script:
    - cd python-tests
    - python3 test.py