name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install
      - run: npm test

  web-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install python deps
        run: |
          python -m pip install --upgrade pip
          pip install selenium
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup chrome and chromedriver
        run: |
          # Install chrome
          wget --quiet https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || apt-get -qq install -y -f
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          # Install chromedriver
          wget https://chromedriver.storage.googleapis.com/77.0.3865.40/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          mv chromedriver /usr/bin/chromedriver
          chmod +x /usr/bin/chromedriver
      - name: Run the web tests
        run: |
          cd python-tests
          python3 test.py
